/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/models/cyberpunk_table.glb -o src/components/models/CyberpunkTableModel.tsx -t 
Author: Rohit3DAsset (https://sketchfab.com/Rohit3Dasset)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-table-c4c2950bd73749088238d59abf6ac6c6
Title: Cyberpunk Table
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCube1_Tb_Tex_0: THREE.Mesh
    pCube2_Tb_Tex_0: THREE.Mesh
  }
  materials: {
    Tb_Tex: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cyberpunk_table.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={20.85}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.pCube1_Tb_Tex_0.geometry} material={materials.Tb_Tex} />
          <mesh geometry={nodes.pCube2_Tb_Tex_0.geometry} material={materials.Tb_Tex} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cyberpunk_table.glb')
