/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/macbook_air_m2.glb -t -o src/components/generated/MacBookModel.tsx 
Author: rtql8d (https://sketchfab.com/rtql8d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-air-m2-786fa23d402a4f90ae36c4168997f9cc
Title: MacBook Air M2
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
  }
  materials: {
    ['Aluminum_-_Anodized_Glossy_Grey']: THREE.MeshStandardMaterial
    ['Aluminum_-_Anodized_Glossy_Grey_keyboard.jpg']: THREE.MeshStandardMaterial
    ['Glass_-_Heavy_Color']: THREE.MeshStandardMaterial
    ['Plastic_-_Translucent_Matte_Gray']: THREE.MeshStandardMaterial
    Acrylic_Clear: THREE.MeshStandardMaterial
    ['Bronze_-_Polished']: THREE.MeshStandardMaterial
    ['Rubber_-_Soft']: THREE.MeshStandardMaterial
    ['Steel_-_Satin']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/macbook_air_m2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Aluminum_-_Anodized_Glossy_Grey']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Aluminum_-_Anodized_Glossy_Grey_keyboard.jpg']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Glass_-_Heavy_Color']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Plastic_-_Translucent_Matte_Gray']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Acrylic_Clear} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Bronze_-_Polished']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Rubber_-_Soft']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Steel_-_Satin']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/macbook_air_m2.glb')
