/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/models/modern_minimalist_phone_stand.glb -o src/components/models/PhoneStandModel.tsx -t 
Author: Skecthfab Pro (https://sketchfab.com/callsudhir8087)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-minimalist-phone-stand-3c6ca5bc27c6461781ef874fc4b604b6
Title: Modern Minimalist Phone Stand
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Upper_support_Black_0: THREE.Mesh
    Reference_2_Black002_0: THREE.Mesh
    Reference_2_Rubber002_0: THREE.Mesh
    Reference_1_Black001_0: THREE.Mesh
    Reference_1_Rubber001_0: THREE.Mesh
    Lower_support_Black_0: THREE.Mesh
    Base_Black_0: THREE.Mesh
    Base_Rubber_pattern_0: THREE.Mesh
    Phone_Stand_Black_0: THREE.Mesh
    Phone_Stand_Rubber_0: THREE.Mesh
    Phone_Stand_Name_0: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    ['Black.002']: THREE.MeshStandardMaterial
    ['Rubber.002']: THREE.MeshStandardMaterial
    ['Black.001']: THREE.MeshStandardMaterial
    ['Rubber.001']: THREE.MeshStandardMaterial
    Rubber_pattern: THREE.MeshStandardMaterial
    Rubber: THREE.MeshStandardMaterial
    Name: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/modern_minimalist_phone_stand.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Phone_Stand_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Phone_Stand_Rubber_0.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.Phone_Stand_Name_0.geometry} material={materials.Name} />
          <mesh geometry={nodes.Upper_support_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Reference_2_Black002_0.geometry} material={materials['Black.002']} />
          <mesh geometry={nodes.Reference_2_Rubber002_0.geometry} material={materials['Rubber.002']} />
          <mesh geometry={nodes.Reference_1_Black001_0.geometry} material={materials['Black.001']} />
          <mesh geometry={nodes.Reference_1_Rubber001_0.geometry} material={materials['Rubber.001']} />
          <mesh geometry={nodes.Lower_support_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Base_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Base_Rubber_pattern_0.geometry} material={materials.Rubber_pattern} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/modern_minimalist_phone_stand.glb')
