/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/models/gaming_table_red__black.glb -o src/components/models/GamingTableModel.tsx -t 
Author: mfkffzl (https://sketchfab.com/mfkffzl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-table-red-black-98d12a5c02bc426c9a7a7fcf2622cf16
Title: Gaming Table (red / black)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
  }
  materials: {
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/gaming_table_red__black.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.028']} position={[0, 2.077, 0.229]} rotation={[0, 0, -Math.PI]} scale={[-0.345, 0.018, 0.506]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.029']} position={[0.36, 2.076, 0.648]} rotation={[0, -1.027, -Math.PI]} scale={[-0.061, 0.018, 0.067]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.030']} position={[0.346, 2.077, 0.18]} rotation={[0, 0, -Math.PI]} scale={[-0.068, 0.017, 0.454]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.018']} position={[1.232, 2.077, 0.379]} rotation={[Math.PI, -1.565, 0]} scale={[-0.293, 0.018, 0.842]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.025']} position={[0.366, 2.076, -0.236]} rotation={[0, -1.259, -Math.PI]} scale={[-0.059, 0.018, 0.069]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.024']} position={[1.236, 2.077, 0.084]} rotation={[Math.PI, -1.565, 0]} scale={[-0.354, 0.018, 0.842]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.027']} position={[0.94, 2.077, -0.255]} rotation={[0, -1.566, -Math.PI]} scale={[-0.058, 0.017, 0.535]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.026']} position={[1.514, 2.076, -0.236]} rotation={[0, 1.217, -Math.PI]} scale={[-0.059, 0.018, 0.069]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material.023']} position={[1.528, 2.075, 0.655]} rotation={[-Math.PI, 0.609, 0]} scale={[-0.061, 0.018, 0.067]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.021']} position={[1.882, 2.077, 0.239]} rotation={[0, 0, -Math.PI]} scale={[-0.345, 0.018, 0.506]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.020']} position={[2.443, 2.077, 0.239]} rotation={[0, 0, -Math.PI]} scale={[-0.345, 0.018, 0.506]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.019']} position={[2.374, 2.077, 1.202]} rotation={[0, 0, -Math.PI]} scale={[-0.416, 0.018, 0.506]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.032']} position={[-0.376, 2.086, 0.232]} rotation={[0, 0, 2.894]} scale={[-0.068, 0.021, 0.507]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Material.031']} position={[-0.482, 2.11, 0.229]} rotation={[0, 0, -Math.PI]} scale={[-0.051, 0.005, 0.505]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.033']} position={[0.976, 2.075, 0.663]} rotation={[Math.PI, -1.567, 0]} scale={[-0.013, 0.017, 0.542]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['Material.033']} position={[0.945, 2.075, -0.307]} rotation={[Math.PI, -1.567, 0]} scale={[-0.013, 0.017, 0.533]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['Material.033']} position={[2.171, 2.075, -0.26]} rotation={[Math.PI, -1.569, 0]} scale={[-0.013, 0.017, 0.613]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['Material.033']} position={[-0.016, 2.075, -0.268]} rotation={[Math.PI, -1.569, 0]} scale={[-0.013, 0.017, 0.337]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.033']} position={[0.006, 2.075, 0.724]} rotation={[Math.PI, -1.569, 0]} scale={[-0.013, 0.017, 0.337]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['Material.033']} position={[1.872, 2.075, 0.735]} rotation={[Math.PI, -1.569, 0]} scale={[-0.013, 0.017, 0.337]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['Material.033']} position={[2.785, 2.075, 0.719]} rotation={[Math.PI, -0.005, 0]} scale={[-0.013, 0.017, 0.993]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials['Material.033']} position={[1.962, 2.075, 1.224]} rotation={[Math.PI, -0.005, 0]} scale={[-0.013, 0.017, 0.478]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials['Material.033']} position={[2.378, 2.075, 1.702]} rotation={[Math.PI, -1.569, 0]} scale={[-0.013, 0.017, 0.426]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['Material.033']} position={[1.483, 2.075, 0.698]} rotation={[Math.PI, -0.963, 0]} scale={[-0.01, 0.017, 0.071]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['Material.033']} position={[0.395, 2.075, 0.692]} rotation={[-Math.PI, 1.009, 0]} scale={[-0.01, 0.017, 0.071]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['Material.033']} position={[0.358, 2.075, -0.291]} rotation={[-Math.PI, 1.254, 0]} scale={[-0.01, 0.017, 0.071]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials['Material.033']} position={[1.537, 2.075, -0.285]} rotation={[Math.PI, -1.227, 0]} scale={[-0.01, 0.017, 0.071]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials['Material.033']} position={[-0.522, 2.108, 0.228]} rotation={[Math.PI, -0.002, 0]} scale={[-0.013, 0.005, 0.503]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials['Material.033']} position={[-0.366, 2.085, 0.735]} rotation={[1.648, 1.382, 1.455]} scale={[0.006, 0.016, 0.054]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials['Material.033']} position={[-0.476, 2.107, 0.735]} rotation={[2.344, 1.55, 0.757]} scale={[0.006, 0.005, 0.061]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['Material.033']} position={[-0.466, 2.094, 0.735]} rotation={[1.631, 1.331, 1.471]} scale={[0.006, 0.005, 0.057]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['Material.033']} position={[-0.449, 2.097, 0.735]} rotation={[1.631, 1.331, 1.471]} scale={[0.007, 0.006, 0.033]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['Material.033']} position={[-0.427, 2.099, 0.735]} rotation={[1.631, 1.331, 1.471]} scale={[0.007, 0.006, 0.016]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['Material.033']} position={[-0.366, 2.085, -0.275]} rotation={[1.648, 1.382, 1.455]} scale={[0.006, 0.016, 0.054]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials['Material.033']} position={[-0.476, 2.107, -0.275]} rotation={[2.344, 1.55, 0.757]} scale={[0.006, 0.005, 0.061]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials['Material.033']} position={[-0.466, 2.094, -0.275]} rotation={[1.631, 1.331, 1.471]} scale={[0.006, 0.005, 0.057]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials['Material.033']} position={[-0.449, 2.097, -0.275]} rotation={[1.631, 1.331, 1.471]} scale={[0.007, 0.006, 0.033]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials['Material.033']} position={[-0.427, 2.099, -0.275]} rotation={[1.631, 1.331, 1.471]} scale={[0.007, 0.006, 0.016]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials['Material.018']} position={[2.189, 1.756, -0.253]} rotation={[-1.587, -1.565, 0]} scale={[-0.313, 0.018, 0.601]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials['Material.018']} position={[0.945, 1.756, -0.286]} rotation={[-1.587, -1.565, 0]} scale={[-0.313, 0.018, 0.55]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials['Material.018']} position={[-0.02, 1.756, -0.253]} rotation={[-1.587, -1.565, 0]} scale={[-0.313, 0.018, 0.331]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials['Material.018']} position={[0.339, 1.756, -0.266]} rotation={[3.125, 1.233, 1.57]} scale={[0.313, 0.018, 0.063]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials['Material.018']} position={[1.55, 1.756, -0.272]} rotation={[0.013, 1.14, -1.599]} scale={[0.313, 0.018, 0.063]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials['Material.018']} position={[2.777, 1.754, 0.721]} rotation={[-3.136, 0.001, -1.554]} scale={[-0.313, 0.018, 0.999]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials['Material.018']} position={[2.359, 1.756, 1.702]} rotation={[-1.587, -1.565, 0]} scale={[-0.313, 0.018, 0.411]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials['Material.018']} position={[-0.522, 1.775, 0.228]} rotation={[-3.136, 0.001, -1.554]} scale={[-0.331, 0.018, 0.514]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials['Material.018']} position={[-0.425, 1.769, -0.262]} rotation={[2.791, 1.555, 1.905]} scale={[0.324, 0.019, 0.086]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials['Material.033']} position={[-0.521, 1.777, 0.73]} rotation={[-1.561, 0.018, 0]} scale={[-0.018, 0.017, 0.333]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials['Material.033']} position={[1.959, 1.766, 1.704]} rotation={[-1.59, 0.018, 0]} scale={[-0.018, 0.015, 0.318]} />
    </group>
  )
}

useGLTF.preload('/models/gaming_table_red__black.glb')
