/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/iphone_16_plus.glb -t -o src/components/generated/IPhoneModel.tsx 
Author: WhatIsLove (https://sketchfab.com/vladgutu11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-16-plus-c1719ed762a7412d933f3ddef0ce2929
Title: Iphone 16 Plus
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
    defaultMaterial_5: THREE.Mesh
    defaultMaterial_6: THREE.Mesh
    defaultMaterial_7: THREE.Mesh
    defaultMaterial_8: THREE.Mesh
    defaultMaterial_9: THREE.Mesh
    defaultMaterial_10: THREE.Mesh
    defaultMaterial_11: THREE.Mesh
    defaultMaterial_12: THREE.Mesh
    defaultMaterial_13: THREE.Mesh
  }
  materials: {
    Screen_Glass: THREE.MeshStandardMaterial
    Antenna: THREE.MeshStandardMaterial
    Glass_Camera_Logo: THREE.MeshStandardMaterial
    Back_Cover: THREE.MeshStandardMaterial
    Screen_Rim: THREE.MeshStandardMaterial
    Grill_USB: THREE.MeshStandardMaterial
    Camera_Pixel_Glass_002: THREE.MeshStandardMaterial
    Camera_Pixel__002: THREE.MeshStandardMaterial
    Plastic: THREE.MeshStandardMaterial
    Rim_Buttons: THREE.MeshStandardMaterial
    Flash_Glass_002: THREE.MeshStandardMaterial
    Flash_002: THREE.MeshStandardMaterial
    Screen_BG: THREE.MeshStandardMaterial
    Screw: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/iphone_16_plus.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Screen_Glass} visible={false} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Antenna} />
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Glass_Camera_Logo} />
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Back_Cover} />
            <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Screen_Rim} />
            <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Grill_USB} />
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Camera_Pixel_Glass_002} />
            <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Camera_Pixel__002} />
            <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Plastic} />
            <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Rim_Buttons} />
            <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Flash_Glass_002} />
            <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.Flash_002} />
            <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.Screen_BG} visible={false} />
            <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Screw} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/iphone_16_plus.glb')
