/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/desk_lamp.glb -t -o src/components/generated/DeskLampModel.tsx 
Author: uday (https://sketchfab.com/udayjeet)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/desk-lamp-2450ec6d3ec84341b28931fe67e063ce
Title: Desk lamp
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    lamp: THREE.MeshStandardMaterial
    wire: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/desk_lamp.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lamp} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.wire} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/desk_lamp.glb')
