/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ficus_bonsai.glb -t -o src/components/generated/FicusBonsaiModel.tsx 
Author: Zgon (https://sketchfab.com/Z-gon)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/ficus-bonsai-f420ea9edb914e1b9b7adebbacecc7d8
Title: Ficus Bonsai
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_Pot_0: THREE.Mesh
    Cube_Bark_0: THREE.Mesh
    Cube_LeafSet_0: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    Bark: THREE.MeshStandardMaterial
    LeafSet: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/ficus_bonsai.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.11}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <group scale={100}>
            <mesh geometry={nodes.Cube_Pot_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube_Bark_0.geometry} material={materials.Bark} />
            <mesh geometry={nodes.Cube_LeafSet_0.geometry} material={materials.LeafSet} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ficus_bonsai.glb')
